mod 'puppetlabs/apache', :latest
mod 'puppetlabs/concat', :latest
mod 'puppetlabs/firewall', :latest
mod 'puppetlabs/gcc', :latest
mod 'puppetlabs/git', :latest
mod 'puppetlabs/inifile', :latest
mod 'puppet/make', :latest
mod 'puppetlabs/ntp', :latest
mod 'puppetlabs/pe_gem', :latest
mod 'zack/r10k', :latest
mod 'puppetlabs/ruby', :latest
mod 'puppet/staging', :latest
mod 'puppetlabs/stdlib', :latest
mod 'puppetlabs/vcsrepo', :latest
